# Generated by Django 3.2.9 on 2021-12-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211203_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRubbish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_rubbish')),
            ],
        ),
    ]
